### ISSUE TITLE
傷害浮動

### ISSUE THREAD

**Issue by homu-gamepress** [eight04/mgcm-skill-data#2]
> 值傷害浮動 - 隨機乘上 0.985, 0.995, 1.005, 1.015 其中一個。

 隨機乘上是 0.98, 0.99, 1.00, 1.01

**Comment by eight04** [comment]
哦？這是拆包的資料嗎？若是真的，目前的技能倍率需要再乘上 `1 / 0.995`

**Comment by homu-gamepress** [comment]
英玩研究的成果。用這樣的浮動技能倍率比較簡單，只需2位數。デモンズスタイルアラクネ 為 4.3/3.3／0等等。

**Comment by eight04** [comment]
測試了一下，這樣倍率的確比較接近第二位小數，誤差大約 0.0002。我想以後新測的數字就以第二高的傷害為準。至於在此之前測出來的資料，我想可以發個 PR 把所有的值都 / 0.995？或是你有更新的資料可以直接用？

**Comment by homu-gamepress** [comment]
https://docs.google.com/spreadsheets/d/1N80A2Uz0lQe8COz3e_xWOePh0_RIMq0hYxkgsMv0CWI/edit#gid=1428786078

**Comment by homu-gamepress** [comment]
介紹 https://www.reddit.com/r/magicami/comments/jxerjq/skill_multiplier_research_results_strongest/

**Comment by eight04** [comment]
太厲害了！這包括了所有已實裝的服裝，對嗎？甚至連 DPS Ranking 都有，完美達到我原先的目的。我會修改 README 並將倍率表指向這個表格。

About special atk bonus: there are two types of skills that introduce extra bonus to the formula. Take [Ruffian Princess Lilly](https://appmedia.jp/magicami/4073218) as an example. In skill description, skill 1 uses the word "比例" (in proportion to...) and skill 2 uses the word "依存" (depending on...):

* In the first situation, I think there is a ratio that converts HP into atk i.e. special atk grows linearly with HP. This also matches some data in the repo but I don't have enough data to prove it.
* In the second situation, the skill ignores the atk of the dress completely, which also means that atk buff doesn't affect the damage at all. In this case, there is no way to find a "skill modifier" because we don't know how to calculate special atk. I think we can define skill modifier as 1 and try to find the relation between HP and special atk.

**Comment by homu-gamepress** [comment]
我們還差幾件英版的服裝，但大部分以你的公式算好了。

special atk例外。在我們的研究好像比ReadMe有些差別。

**Comment by eight04** [comment]
Another note to the first situation: IIRC when [Magica2061 依子](https://appmedia.jp/magicami/3790348) get the speed buff (*1.3), special atk also *1.3.

**Comment by homu-gamepress** [comment]
Ruffian Princess Lilly 
s2 skill_mod 0 special atk 0.1633556814
s3 skill_mod 0 special atk 0.3060257135

**Comment by eight04** [comment]
> Ruffian Princess Lilly
> s2 skill_mod 0 special atk 0.1633556814
> s3 skill_mod 0 special atk 0.3060257135

這是什麼意思？

另外，有沒有說明 Strongest Dress 是如何算出來的？是以各禮服的 atk * skill_mod * skill_hit？atk 有考慮等級、副裝、還有寶珠嗎？

**Comment by homu-gamepress** [comment]
Strongest Dress is calculated with a rolling average of the dress skill rotation:

      s1_mod * s1_bonus
     + 1 / (s2_cd) * (s2_mod * s2_bonus - s1_mod * s1_bonus)
     + 1 / (s3_cd) * (s3_mod * s3_bonus - s1_mod * s1_bonus)
       
It's a rough estimate and do not account for atk.  Other players in the English community have implemented more serious simulation that account for Total ATK and full loop simulation though:

![image](https://user-images.githubusercontent.com/54113629/99895883-0cd8dc80-2c40-11eb-9240-25e40708a976.png)

**Comment by eight04** [comment]
Where can I find their project?

I just build a database including dress status and skill bonus/CT:
https://github.com/eight04/mgcm-skill-data/blob/master/dress-db.yml

Now we just have to find out how special atk works.

**Comment by homu-gamepress** [comment]
He said to get in touch with him on discord: https://discord.gg/DXzb6gQ  @ bop#1274
